CREATE TABLE BOOK(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
TITLE VARCHAR(32),
AUTHOR_ID BIGINT NOT NULL,
PUBLISHER VARCHAR(32),
EDITION VARCHAR(32),
ISBN VARCHAR(32),
PUBLISHING_DATE DATE,
CHAPTER_ID BIGINT NOT NULL
);

CREATE TABLE AUTHOR(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
GIVEN_NAME VARCHAR(32),
SURNAME VARCHAR(32),
DATE_OF_BIRTH DATE,
BIO VARCHAR(32)
);

CREATE TABLE CHAPTER(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
TITLE VARCHAR(32),
START_PAGE BIGINT,
NUMBER_OF_PAGES BIGINT,
BOOK_ID BIGINT NOT NULL
);

ALTER TABLE BOOK ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID);
ALTER TABLE BOOK ADD FOREIGN KEY (CHAPTER_ID) REFERENCES CHAPTER(ID);
